USE ROLE SYSADMIN;
-- USE DATABASE --
USE DATABASE SALES_DWH;
USE SCHEMA SOURCE;
LIST @MY_INTERNAL_STG / SOURCE = IN;
SHOW FILE FORMATS;
DESC FILE FORMAT CSV_FORMAT;
---READ DATA FROM INTERNAL STAGE USING FILE FORMAT--
SELECT T.$1::TEXT AS ORDER_ID,
    T.$2::TEXT AS CUSTOMER_NAME,
    T.$3::TEXT AS MOBILE_KEY,
    T.$4::NUMBER AS ORDER_QUANTITY,
    T.$5::NUMBER AS UNIT_PRICE,
    T.$6::NUMBER AS ORDER_VALAUE,
    T.$7::TEXT AS PROMOTION_CODE,
    T.$8::NUMBER(10, 2) AS FINAL_ORDER_AMOUNT,
    T.$9::NUMBER(10, 2) AS TAX_AMOUNT,
    T.$10::DATE AS ORDER_DT,
    T.$11::TEXT AS PAYMENT_STATUS,
    T.$12::TEXT AS SHIPPING_STATUS,
    T.$13::TEXT AS PAYMENT_METHOD,
    T.$14::TEXT AS PAYMENT_PROVIDER,
    T.$15::TEXT AS MOBILE,
    T.$16::TEXT AS SHIPPING_ADDRESS
FROM @MY_INTERNAL_STG / SALES / SOURCE = IN / FORMAT = CSV / (FILE_FORMAT => 'SALES_DWH.SOURCE.CSV_FORMAT') T;
-- INTERNAL STAGE - QUERY THE PARQUET DATA FILE FORMAT
SELECT $1 :"ORDER ID"::TEXT AS ORDE_ID,
    $1 :"CUSTOMER NAME"::TEXT AS CUSTOMER_NAME,
    $1 :"MOBILE MODEL"::TEXT AS MOBILE_KEY,
    TO_NUMBER($1 :"QUANTITY") AS QUANTITY,
    TO_NUMBER($1 :"PRICE PER UNIT") AS UNIT_PRICE,
    TO_DECIMAL($1 :"TOTAL PRICE") AS TOTAL_PRICE,
    $1 :"PROMOTION CODE"::TEXT AS PROMOTION_CODE,
    $1 :"ORDER AMOUNT"::NUMBER(10, 2) AS ORDER_AMOUNT,
    TO_DECIMAL($1 :"TAX") AS TAX,
    $1 :"ORDER DATE"::DATE AS ORDER_DT,
    $1 :"PAYMENT STATUS"::TEXT AS PAYMENT_STATUS,
    $1 :"SHIPPING STATUS"::TEXT AS SHIPPING_STATUS,
    $1 :"PAYMENT METHOD"::TEXT AS PAYMENT_METHOD,
    $1 :"PAYMENT PROVIDER"::TEXT AS PAYMENT_PROVIDER,
    $1 :"PHONE"::TEXT AS PHONE,
    $1 :"DELIVERY ADDRESS"::TEXT AS SHIPPING_ADDRESS
FROM @MY_INTERNAL_STG / SALES / SOURCE = US / FORMAT = PARQUET / (
        FILE_FORMAT => 'SALES_DWH.SOURCE.MY_PARQUET_FORMAT'
    );
-- INTERNAL STAGE - QUERY THE JSON DATA FILE FORMAT
SELECT $1 :"ORDER ID"::TEXT AS ORDE_ID,
    $1 :"CUSTOMER NAME"::TEXT AS CUSTOMER_NAME,
    $1 :"MOBILE MODEL"::TEXT AS MOBILE_KEY,
    TO_NUMBER($1 :"QUANTITY") AS QUANTITY,
    TO_NUMBER($1 :"PRICE PER UNIT") AS UNIT_PRICE,
    TO_DECIMAL($1 :"TOTAL PRICE") AS TOTAL_PRICE,
    $1 :"PROMOTION CODE"::TEXT AS PROMOTION_CODE,
    $1 :"ORDER AMOUNT"::NUMBER(10, 2) AS ORDER_AMOUNT,
    TO_DECIMAL($1 :"TAX") AS TAX,
    $1 :"ORDER DATE"::DATE AS ORDER_DT,
    $1 :"PAYMENT STATUS"::TEXT AS PAYMENT_STATUS,
    $1 :"SHIPPING STATUS"::TEXT AS SHIPPING_STATUS,
    $1 :"PAYMENT METHOD"::TEXT AS PAYMENT_METHOD,
    $1 :"PAYMENT PROVIDER"::TEXT AS PAYMENT_PROVIDER,
    $1 :"PHONE"::TEXT AS PHONE,
    $1 :"DELIVERY ADDRESS"::TEXT AS SHIPPING_ADDRESS
FROM @SALES_DWH.SOURCE.MY_INTERNAL_STG / SALES / SOURCE = FR / FORMAT = JSON / (FILE_FORMAT => SALES_DWH.SOURCE.MY_JSON_FORMAT);
SELECT T.$1::DATE AS EXCHANGE_DT,
    TO_DECIMAL(T.$2) AS USD2USD,
    TO_DECIMAL(T.$3, 18, 10) AS USD2EU,
    TO_DECIMAL(T.$4, 18, 10) AS USD2CAN,
    TO_DECIMAL(T.$5, 18, 10) AS USD2UK,
    TO_DECIMAL(T.$6, 18, 10) AS USD2INR,
    TO_DECIMAL(T.$7, 18, 10) AS USD2JP
FROM @SALES_DWH.SOURCE.MY_INTERNAL_STG / EXCHANGE - RATE - DATA.CSV (
        FILE_FORMAT => 'SALES_DWH.COMMON_SALES.CSV_FORMAT'
    ) T;