USE ROLE SYSADMIN;
-- USE DATABASE --
USE DATABASE SALES_DWH;
-- CREATE SCHEMAS --
USE SCHEMA COMMON_SALES;
COPY INTO SALES_DWH.COMMON_SALES.EXCHANGE_RATE FORM (
    SELECT T.$1::DATE AS EXCHANGE_DT,
        TO_DECIMAL(T.$2) AS USD2USD,
        TO_DECIMAL(T.$3, 18, 10) AS USD2EU,
        TO_DECIMAL(T.$4, 18, 10) AS USD2CAN,
        TO_DECIMAL(T.$5, 18, 10) AS USD2UK,
        TO_DECIMAL(T.$6, 18, 10) AS USD2INR,
        TO_DECIMAL(T.$7, 18, 10) AS USD2JP
    FROM @SALES_DWH.SOURCE.MY_INTERNAL_STG/exchange-rate-data.CSV (
            FILE_FORMAT => 'SALES_DWH.COMMON_SALES.CSV_FORMAT'
        ) T
)