USE ROLE SYSADMIN;
-- USE DATABASE --
USE DATABASE SALES_DWH;
-- USE SCHEMAS --
USE SCHEMA SOURCE;

CREATE OR REPLACE SEQUENCE IN_SALES_ORDER_SEQ 
  START = 1 
  INCREMENT = 1 
COMMENT='THIS IS SEQUENCE FOR INDIA SALES ORDER TABLE';

CREATE OR REPLACE SEQUENCE US_SALES_ORDER_SEQ 
  START = 1 
  INCREMENT = 1 
  COMMENT='THIS IS SEQUENCE FOR USA SALES ORDER TABLE';

CREATE OR REPLACE SEQUENCE FR_SALES_ORDER_SEQ 
  START = 1 
  INCREMENT = 1 
  COMMENT='THIS IS SEQUENCE FOR FRANCE SALES ORDER TABLE';