-- USE SYSADMIN ROLE TO CREATE OBJECTS --
USE ROLE SYSADMIN;
-- USE DATABASE --
USE DATABASE SALES_DWH;
-- CREATE SCHEMAS --
CREATE SCHEMA IF NOT EXISTS SOURCE;
CREATE SCHEMA IF NOT EXISTS CURATED;
CREATE SCHEMA IF NOT EXISTS CONSUMPTION;
CREATE SCHEMA IF NOT EXISTS COMMON_SALES;