-- USE SYSADMIN ROLE TO CREATE OBJECTS --
USE ROLE SYSADMIN;

CREATE OR REPLACE WAREHOUSE SNOWPARK_ETL_WH
WITH
WAREHOUSE_SIZE = 'MEDIUM'
WAREHOUSE_TYPE = 'STANDARD'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE
MIN_CLUSTER_COUNT = 1
MAX_CLUSTER_COUNT = 1
SCALING_POLICY = 'STANDARD';

USE ROLE USERADMIN;

CREATE USER SNOWPARK_USER
PASSWORD = 'test@1234'
comment = 'This user is created to use snowpark'
default_role = SYSADMIN
DEFAULT_SECONDARY_ROLES = ('ALL')
MUST_CHANGE_PASSWORD = FALSE;

GRANT ROLE SYSADMIN TO SNOWPARK_USER;
GRANT USAGE ON WAREHOUSE SNOWPARK_ETL_WH TO ROLE SYSADMIN;

