USE ROLE SYSADMIN;
-- USE DATABASE --
USE DATABASE SALES_DWH;
-- USE SCHEMAS --
USE SCHEMA SOURCE;
-- INDIA SALES TABLE IN SOURCE SCHEMA (CSV FILE)
CREATE OR REPLACE TRANSIENT TABLE IN_SALES_ORDER (
        SALES_ORDER_KEY NUMBER(38, 0),
        ORDER_ID VARCHAR(),
        CUSTOMER_NAME VARCHAR(),
        MOBILE_KEY VARCHAR(),
        ORDER_QUANTITY NUMBER(38, 0),
        UNIT_PRICE NUMBER(38, 0),
        ORDER_VALAUE NUMBER(38, 0),
        PROMOTION_CODE VARCHAR(),
        FINAL_ORDER_AMOUNT NUMBER(10, 2),
        TAX_AMOUNT NUMBER(10, 2),
        ORDER_DT DATE,
        PAYMENT_STATUS VARCHAR(),
        SHIPPING_STATUS VARCHAR(),
        PAYMENT_METHOD VARCHAR(),
        PAYMENT_PROVIDER VARCHAR(),
        MOBILE VARCHAR(),
        SHIPPING_ADDRESS VARCHAR(),
        STG_FILE_NAME VARCHAR(),
        STG_ROW_NUMBER NUMBER(38, 0),
        STG_LAST_MODIFIED TIMESTAMP_NTZ(9)
    );
-- US SALES TABLE IN SOURCE SCHEMA (PARQUET FILE)
CREATE OR REPLACE TRANSIENT TABLE US_SALES_ORDER (
        SALES_ORDER_KEY NUMBER(38, 0),
        ORDER_ID VARCHAR(),
        CUSTOMER_NAME VARCHAR(),
        MOBILE_KEY VARCHAR(),
        ORDER_QUANTITY NUMBER(38, 0),
        UNIT_PRICE NUMBER(38, 0),
        ORDER_VALAUE NUMBER(38, 0),
        PROMOTION_CODE VARCHAR(),
        FINAL_ORDER_AMOUNT NUMBER(10, 2),
        TAX_AMOUNT NUMBER(10, 2),
        ORDER_DT DATE,
        PAYMENT_STATUS VARCHAR(),
        SHIPPING_STATUS VARCHAR(),
        PAYMENT_METHOD VARCHAR(),
        PAYMENT_PROVIDER VARCHAR(),
        PHONE VARCHAR(),
        SHIPPING_ADDRESS VARCHAR(),
        STG_FILE_NAME VARCHAR(),
        STG_ROW_NUMBER NUMBER(38, 0),
        STG_LAST_MODIFIED TIMESTAMP_NTZ(9)
    );
-- FRANCE SALES TABLE IN SOURCE SCHEMA (JSON FILE)
CREATE OR REPLACE TRANSIENT TABLE FR_SALES_ORDER (
        SALES_ORDER_KEY NUMBER(38, 0),
        ORDER_ID VARCHAR(),
        CUSTOMER_NAME VARCHAR(),
        MOBILE_KEY VARCHAR(),
        ORDER_QUANTITY NUMBER(38, 0),
        UNIT_PRICE NUMBER(38, 0),
        ORDER_VALAUE NUMBER(38, 0),
        PROMOTION_CODE VARCHAR(),
        FINAL_ORDER_AMOUNT NUMBER(10, 2),
        TAX_AMOUNT NUMBER(10, 2),
        ORDER_DT DATE,
        PAYMENT_STATUS VARCHAR(),
        SHIPPING_STATUS VARCHAR(),
        PAYMENT_METHOD VARCHAR(),
        PAYMENT_PROVIDER VARCHAR(),
        PHONE VARCHAR(),
        SHIPPING_ADDRESS VARCHAR(),
        STG_FILE_NAME VARCHAR(),
        STG_ROW_NUMBER NUMBER(38, 0),
        STG_LAST_MODIFIED TIMESTAMP_NTZ(9)
    );